---
title: babelmixr2 and PopED
author: Matthew Fidler
date: '2024-11-05'
slug: []
categories: [rxode2, monolix2rx, monolix, nonmem2rx, nonmem, babelmixr2, PopED]
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rxode2)
library(nlmixr2)
library(babelmixr2)
```
# New babelmixr2 integrates PopED

I am excited to announce today a new version of `babelmixr2` has been
released that streamlines creating fast, efficient `PopED` databases
for optimal design.

With the `babelmixr2` package you can:

- Import your `NONMEM` model to `rxode2`/`nlmixr2` format using
  [nonmem2rx](https://nlmixr2.github.io/nonmem2rx/)

- Import your `Monolix` model to `rxode2`/`nlmixr2` using
  [monolix2rx](https://nlmixr2.github.io/monolix2rx)

- Use your existing `nlmixr2` model or create your own
  `rxode2`/`nlmixr2` model to do optimal design.

## Key notes in using `PopED` using `babelmixr2`

- `babelmixr2` requires a design dataset instead of design options,
  which translates to design options like `xt`, `model_switch` etc,
  (described
  [here](https://nlmixr2.github.io/babelmixr2/articles/PopED.html#popedbabelmixr2-event-table-description))

- You can get the underlying `PopED` code from the `nlmixr2` model if
  you want (as [described in the annotated PopED
  example](https://nlmixr2.github.io/babelmixr2/articles/PopED.html))

- `babelmixr2` loads models into memory and needs to keep track of
  which model is loaded. To help this you need to use
  `babel.poped.database` in place of `create.poped.database` when
  modifying babelmixr2 generated `PopED` databases.  If this isn't
  done, there is a chance that the model loaded will not be the
  expected loaded model and may either crash R or possibly give incorrect
  results.

- `babelmixr2` translates all error components to variances instead of
  the standard deviations in the `nlmixr2`/`rxode2` model.

- When there are covariances in the `omega` specification, they will
  be identified as `D[#,#]` in the `PopED` output. To see what these
  numbers refer to it is helpful to see the name translations with
  `$popedD`.

- Depending on your options, `babelmixr2` may literally fix the model
  components, which means indexes may be different than you
  expect. The best way to get the correct index is use the
  `babelmixr2` function `babelBpopIdx()` which is useful for using
  `PopED`.

- `babelmixr2` uses model times in creating `PopED` databases;
  therefore models with modeling times in them cannot be used in this translation

- `babelmixr2` does not yet support inter-occasion variability models.

- At the current time, the `ODE` solution used is the [fastest of the
  models tested](https://nlmixr2.github.io/babelmixr2/articles/PopED.html#comparing-method-to-the-speed-of-other-methods), but keep in mind this is problem dependent. To me,
  the most important feature is not the speed of the model, but the
  ease of translating into a `PopED` database from the tools you use
  (like `nlmixr2`, `NONMEM` and `Monolix`).

Many of the `PopED` models were restated as `babelmixr2`/`PopED`
models to show how to use the interface and are included in the
`babelmixr2` package
[here](https://github.com/nlmixr2/babelmixr2/tree/main/inst/poped)


This blog is coming right before the ACoP 2024 conference.

If you want stickers or to talk more about this you can:

- Stop by our poster: [babelmixr2 and PopED: Quick Conversion of NONMEM, Monolix and nlmixr2/rxode2 Models to PopED Optimal Design Analysis](https://cdmcd.co/6vd4Z8)

- Attend our or our nlmixr2 tutorial on Thursday ([Using Past Models to Bridge to
  Open Models and Open Science using nlmixr2](https://blog.nlmixr2.org/courses/acop2024/
)) if you want to talk
  about this a bit more.


Thanks, see you in person soon if you are going to ACoP 2024!
